# Generated by Django 4.1.7 on 2023-10-16 15:22

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termoadesaoada',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='termoadesaoada',
            name='municipio',
        ),
        migrations.AddField(
            model_name='termoadesaoada',
            name='estado_controle_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termoadesaoada_controle_social', to='comum.estado'),
        ),
        migrations.AddField(
            model_name='termoadesaoada',
            name='estado_local_armazenamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termoadesaoada_local_armazenamento', to='comum.estado'),
        ),
        migrations.AddField(
            model_name='termoadesaoada',
            name='estado_prefeitura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termoadesaoada_prefeitura', to='comum.estado'),
        ),
        migrations.AddField(
            model_name='termoadesaoada',
            name='estado_solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termoadesaoada_solicitante', to='comum.estado'),
        ),
        migrations.AddField(
            model_name='termoadesaoada',
            name='municipio_controle_social',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='estado_controle_social', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termoadesaoada_municipio_controle_social', to='comum.municipio'),
        ),
        migrations.AddField(
            model_name='termoadesaoada',
            name='municipio_local_armazenamento',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='estado_local_armazenamento', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termoadesaoada_municipio_local_armazenamento', to='comum.municipio'),
        ),
        migrations.AddField(
            model_name='termoadesaoada',
            name='municipio_prefeitura',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='estado_prefeitura', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termoadesaoada_municipio_prefeitura', to='comum.municipio'),
        ),
        migrations.AddField(
            model_name='termoadesaoada',
            name='municipio_solicitante',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='estado_solicitante', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termoadesaoada_municipio_solicitante', to='comum.municipio'),
        ),
    ]
