# Generated by Django 4.1.7 on 2023-11-10 17:33

import comum.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
        ('registros', '0003_alter_termoadesaoada_cepsolicitante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termoadesaoada',
            name='municipioarmazenamento_id',
        ),
        migrations.RemoveField(
            model_name='termoadesaoada',
            name='municipiocontrolesocial_id',
        ),
        migrations.RemoveField(
            model_name='termoadesaoada',
            name='municipioprefeitura',
        ),
        migrations.RemoveField(
            model_name='termoadesaoada',
            name='municipiosolicitante_id',
        ),
        migrations.RemoveField(
            model_name='termoadesaoada',
            name='municipiounidade_id',
        ),
        migrations.RemoveField(
            model_name='termoadesaoada',
            name='nomemunicipio',
        ),
        migrations.RemoveField(
            model_name='termoadesaoada',
            name='nomemunicipioarmazenamento',
        ),
        migrations.RemoveField(
            model_name='termoadesaoada',
            name='nomemunicipiocontrolesocial',
        ),
        migrations.AddField(
            model_name='termoadesaoada',
            name='estado_entefederativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termoadesaoada_entefederativo', to='comum.estado'),
        ),
        migrations.AddField(
            model_name='termoadesaoada',
            name='municipio_entefederativo',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='estado_entefederativo', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='termoadesaoada_municipio_entefederativo', to='comum.municipio'),
        ),
        migrations.AlterField(
            model_name='termoadesaoada',
            name='arquivo',
            field=models.FileField(blank=True, upload_to='registro_termodesao', verbose_name='ARQUIVO'),
        ),
        migrations.CreateModel(
            name='SolicitacaoADA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibge', models.CharField(blank=True, max_length=20, null=True, verbose_name='IBGE')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='NOME DO SOLICITANTE')),
                ('funcao_gestor', models.CharField(blank=True, max_length=100, null=True, verbose_name='FUNÇÃO')),
                ('cpfsolicitante', models.CharField(blank=True, max_length=20, null=True, validators=[comum.validators.valida_cpf], verbose_name='CPF DO SOLICITANTE')),
                ('emailsolicitante', models.CharField(blank=True, max_length=100, null=True, verbose_name='E-MAIL DO SOLICITANTE')),
                ('telefone1solicitante', models.CharField(blank=True, max_length=20, null=True, verbose_name='TELEFONE 1 DO SOLICITANTE ')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='TIPO')),
                ('cepsolicitante', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP DO SOLICITANTE')),
                ('enderecosolicitante', models.CharField(blank=True, max_length=100, null=True, verbose_name='ENDEREÇO DO SOLICITANTE')),
                ('numerosolicitante', models.CharField(blank=True, max_length=20, null=True, verbose_name='NÚMERO DO SOLICITANTE')),
                ('complementosolicitante', models.CharField(blank=True, max_length=50, null=True, verbose_name='COMPLEMENTO SOLICITANTE')),
                ('bairrosolicitante', models.CharField(blank=True, max_length=100, null=True, verbose_name='BAIRRO DO SOLICITANTE')),
                ('cnpjprefeitura', models.CharField(blank=True, max_length=20, null=True, validators=[comum.validators.valida_cnpj], verbose_name='CNPJ')),
                ('emailprefeitura', models.CharField(blank=True, max_length=150, null=True, verbose_name='E-MAIL DA PREFEITURA')),
                ('cepprefeitura', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP DA PREFEITURA')),
                ('enderecoprefeitura', models.CharField(blank=True, max_length=100, null=True, verbose_name='ENDEREÇO DA PREFEITURA')),
                ('numeroprefeitura', models.CharField(blank=True, max_length=100, null=True, verbose_name='NÚMERO DA PREFEITURA')),
                ('complementoprefeitura', models.CharField(blank=True, max_length=100, null=True, verbose_name='COMPLEMENTO DA PREFEITURA')),
                ('bairroprefeitura', models.CharField(blank=True, max_length=100, null=True, verbose_name='BAIRRO DA PREFEITURA')),
                ('nomeprefeito', models.CharField(blank=True, max_length=100, null=True, verbose_name='NOME DO PREFEITO')),
                ('telefoneprefeito', models.CharField(blank=True, max_length=50, null=True, verbose_name='TELEFONE DO PREFEITO')),
                ('cpfprefeito', models.CharField(blank=True, max_length=20, null=True, validators=[comum.validators.valida_cpf], verbose_name='CPF DO PREFEITO')),
                ('rgprefeito', models.CharField(blank=True, max_length=50, null=True, verbose_name='RG DO PREFEITO')),
                ('orgaorgprefeito', models.CharField(blank=True, max_length=50, null=True, verbose_name='ORGÃO DO RG')),
                ('ufrgprefeito', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('emailprefeito', models.CharField(blank=True, max_length=150, null=True, verbose_name='E-MAIL DO PREFEITO')),
                ('quantidadecestas', models.BigIntegerField(blank=True, null=True, verbose_name='QUANTIDADE DE CESTAS')),
                ('nomelocalarmazenamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='NOME DO LOCAL DE ARMAZENAMENTO')),
                ('ceparmazenamento', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP DO LOCAL DE ARMAZENAMENTO')),
                ('enderecoarmazenamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='ENDEREÇO DO LOCAL DE ARMAZENAMENTO')),
                ('numeroarmazenamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='NÚMERO DO LOCAL DE ARMAZENAMENTO')),
                ('complementoarmazenamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='COMPLEMENTO DO LOCAL DE ARMAZENAMENTO')),
                ('bairroarmazenamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='BAIRRO DO LOCAL DE ARMAZENAMENTO')),
                ('nomelocalcontrolesocial', models.CharField(blank=True, max_length=100, null=True, verbose_name='NOME DO LOCAL DE CONTROLE SOCIAL')),
                ('bairrocontrolesocial', models.CharField(blank=True, max_length=100, null=True, verbose_name='BAIRRO DO CONTROLE SOCIAL')),
                ('numerocontrolesocial', models.CharField(blank=True, max_length=100, null=True, verbose_name='NÚMERO DO CONTROLE SOCIAL')),
                ('complementocontrolesocial', models.CharField(blank=True, max_length=100, null=True, verbose_name='COMPLEMENTO DO CONTROLE SOCIAL')),
                ('cepcontrolesocial', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP DO CONTROLE SOCIAL')),
                ('enderecocontrolesocial', models.CharField(blank=True, max_length=100, null=True, verbose_name='ENDEREÇO DO LOCAL DO CONTROLE SOCIAL')),
                ('telefone1controlesocial', models.CharField(blank=True, max_length=20, null=True, verbose_name='TELEFONE 1')),
                ('telefone2controlesocial', models.CharField(blank=True, max_length=20, null=True, verbose_name='TELEFONE 2')),
                ('emailcontrolesocial', models.CharField(blank=True, max_length=150, null=True, verbose_name='E-MAIL DO CONTROLE SOCIAL')),
                ('dirigentecontrolesocial', models.CharField(blank=True, max_length=150, null=True, verbose_name='DIRETOR DO CONTROLE SOCIAL')),
                ('arquivo', models.FileField(blank=True, upload_to='registro_solicitacao', verbose_name='ARQUIVO')),
                ('situacao', models.CharField(blank=True, choices=[('SOLICITADO', 'SOLICITADO'), ('ACEITO (AGUARDANDO ASSINATURA SEI)', 'ACEITO (AGUARDANDO ASSINATURA SEI)'), ('ACEITO (AGUARDANDO PUBLICACAO NO D.O.U)', 'ACEITO (AGUARDANDO PUBLICACAO NO D.O.U)'), ('ADERIDO', 'ADERIDO'), ('NEGADO', 'NEGADO')], default='SOLICITADO', max_length=60, null=True, verbose_name='SITUAÇÃO')),
                ('observacao', models.TextField()),
                ('data_publicacao_dou', models.DateField(blank=True, null=True, verbose_name='DATA DA PUBLICAÇÃO DOU')),
                ('link_publicacao_dou', models.CharField(blank=True, max_length=200, null=True, verbose_name='LINK DA PUBLICAÇÃO DOU')),
                ('funcao', models.CharField(blank=True, max_length=100, null=True, verbose_name='FUNÇÃO')),
                ('ntermo', models.CharField(blank=True, choices=[('SIM', 'SIM'), ('NAO', 'NAO')], max_length=10, null=True)),
                ('datasolicitacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='DATA DA SOLICITAÇÃO')),
                ('estado_controle_social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_controle_social', to='comum.estado')),
                ('estado_local_armazenamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_local_armazenamento', to='comum.estado')),
                ('estado_prefeitura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_prefeitura', to='comum.estado')),
                ('estado_solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_solicitante', to='comum.estado')),
                ('evento_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registros.tipoeventoada', verbose_name='EVENTO')),
                ('municipio_controle_social', smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='estado_controle_social', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_municipio_controle_social', to='comum.municipio')),
                ('municipio_local_armazenamento', smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='estado_local_armazenamento', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_municipio_local_armazenamento', to='comum.municipio')),
                ('municipio_prefeitura', smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='estado_prefeitura', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_municipio_prefeitura', to='comum.municipio')),
                ('municipio_solicitante', smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='estado_solicitante', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_municipio_solicitante', to='comum.municipio')),
                ('portaria_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registros.tipoportariaada', verbose_name='PORTARIA')),
                ('publico_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registros.tipopublicoada', verbose_name='PÚBLICO')),
            ],
            options={
                'db_table': 'solicitacao_ada',
            },
        ),
    ]
