# Generated by Django 4.1.7 on 2023-11-10 17:33

import comum.validators
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
        ('execucao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoCestasADA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipioentefederativo', models.CharField(blank=True, max_length=100, null=True, verbose_name='MUNICIPIO ENTE FEDERATIVO')),
                ('ibge', models.CharField(blank=True, max_length=20, null=True, verbose_name='IBGE ENTE FEDERATIVO')),
                ('cnpjentefederativo', models.CharField(blank=True, max_length=20, null=True, validators=[comum.validators.valida_cnpj], verbose_name='CNPJ ENTEFEDERATIVO')),
                ('cepentefederativo', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP DO ENTE FEDERATIVO')),
                ('enderecoentefederativo', models.CharField(blank=True, max_length=100, null=True, verbose_name='ENDEREÇO DO ENTE FEDERATIVO')),
                ('numeroentefederativo', models.CharField(blank=True, max_length=100, null=True, verbose_name='NÚMERO DO ENTE FEDERATIVO')),
                ('uf', models.CharField(blank=True, max_length=100, null=True, verbose_name='UF ENTE FEDERATIVO')),
                ('nomeprefeito', models.CharField(blank=True, max_length=100, null=True, verbose_name='NOME DO PREFEITO')),
                ('telefone1entefederativo', models.CharField(blank=True, max_length=20, null=True, verbose_name='TELEFONE 1 RESPONSAVEL')),
                ('telefone2entefederativo', models.CharField(blank=True, max_length=20, null=True, verbose_name='TELEFONE 2')),
                ('emailentefederativo', models.CharField(blank=True, max_length=150, null=True, verbose_name='E-MAIL DO ENTE FEDERATIVO')),
                ('nomeresponsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='NOME DO RESPONSAVEL')),
                ('rgresponsavel', models.CharField(blank=True, max_length=50, null=True, verbose_name='RG DO RESPONSAVEL')),
                ('orgaoresponsavel', models.CharField(blank=True, max_length=50, null=True, verbose_name='ORGÃO DO RG')),
                ('cpfresponsavel', models.CharField(blank=True, max_length=20, null=True, validators=[comum.validators.valida_cpf], verbose_name='CPF DO RESPONSAVEL')),
                ('cargoresponsavel', models.CharField(blank=True, max_length=100, null=True, verbose_name='CARGO DO RESPONSAVEL')),
                ('emailresponsavel', models.CharField(blank=True, max_length=150, null=True, verbose_name='E-MAIL DO RESPONSAVEL')),
                ('telefone1responsavel', models.CharField(blank=True, max_length=20, null=True, verbose_name='TELEFONE RESPONSAVEL')),
                ('setor', models.CharField(blank=True, max_length=100, null=True, verbose_name='SETOR')),
                ('nomecoordenador', models.CharField(blank=True, max_length=100, null=True, verbose_name='NOME DO COORDENADOR')),
                ('cpfcoordenador', models.CharField(blank=True, max_length=20, null=True, validators=[comum.validators.valida_cpf], verbose_name='CPF DO COORDENADOR')),
                ('cargocoordenador', models.CharField(blank=True, max_length=100, null=True, verbose_name='CARGO DO COORDENADOR')),
                ('emailcoordenador', models.CharField(blank=True, max_length=100, null=True, verbose_name='EMAIL DO COORDENADOR')),
                ('telefone1coordenador', models.CharField(blank=True, max_length=20, null=True, verbose_name='TELEFONE 1 COORDENADOR')),
                ('telefone2coordenador', models.CharField(blank=True, max_length=20, null=True, verbose_name='TELEFONE 2 COORDENADOR')),
                ('quantidadecestas', models.BigIntegerField(blank=True, null=True, verbose_name='QUANTIDADE DE CESTAS')),
                ('nomelocalarmazenamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='NOME DO LOCAL DE ARMAZENAMENTO')),
                ('bairroarmazenamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='BAIRRO DO LOCAL DE ARMAZENAMENTO')),
                ('numeroarmazenamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='NÚMERO DO LOCAL DE ARMAZENAMENTO')),
                ('complementoarmazenamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='COMPLEMENTO DO LOCAL DE ARMAZENAMENTO')),
                ('enderecoarmazenamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='ENDERECO DO LOCAL DE ARMAZENAMENTO')),
                ('ceparmazenamento', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP DO LOCAL DE ARMAZENAMENTO')),
                ('nomecontrolesocial', models.CharField(blank=True, max_length=100, null=True, verbose_name='NOME DA ENTIDADE')),
                ('enderecocontrolesocial', models.CharField(blank=True, max_length=100, null=True, verbose_name='ENDERECO DO CONTROLE SOCIAL')),
                ('complementocontrolesocial', models.CharField(blank=True, max_length=100, null=True, verbose_name='COMPLEMENTO DO LOCAL DO CONTROLE SOCIAL')),
                ('cepcontrolesocial', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP CONTROLE SOCIAL')),
                ('telefone1controlesocial', models.CharField(blank=True, max_length=20, null=True, verbose_name='TELEFONE 1 CONTROLE SOCIAL')),
                ('telefone2controlesocial', models.CharField(blank=True, max_length=20, null=True, verbose_name='TELEFONE 2 CONTROLE SOCIAL')),
                ('emailcontrolesocial', models.CharField(blank=True, max_length=150, null=True, verbose_name='E-MAIL DO CONTROLE SOCIAL')),
                ('nomerepresentante', models.CharField(blank=True, max_length=100, null=True, verbose_name='NOME DO REPRESENTANTE')),
                ('cargorepresentante', models.CharField(blank=True, max_length=100, null=True, verbose_name='CARGO DO REPRESENTANTE')),
                ('dataavaliacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='DATA DA AVALIAÇÃO')),
                ('nomeavaliador', models.CharField(blank=True, max_length=100, null=True, verbose_name='NOME DO AVALIADOR')),
                ('notatecnica', models.FileField(blank=True, upload_to='notatecnica_solicitacao_cestas', verbose_name='NOTA TECNICA')),
                ('justificativa', models.TextField(blank=True)),
                ('situacaocestas', models.CharField(blank=True, choices=[('ATIVO', 'ATIVO'), ('INATIVO', 'INATIVO')], default='ATIVO', max_length=60, null=True, verbose_name='SITUAÇÃO')),
                ('sei', models.CharField(blank=True, max_length=100, null=True, verbose_name='NUMERO DO PROCESSO SEI')),
                ('estado_controlesocial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_cesta_controle_social', to='comum.estado')),
                ('estado_entefederativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_cesta_entefederativo', to='comum.estado')),
                ('estado_local_armazenamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_cesta_local_armazenamento', to='comum.estado')),
                ('municipio_controlesocial', smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='estado_controlesocial', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_cesta_municipio_controle_social', to='comum.municipio')),
                ('municipio_entefederativo', smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='estado_entefederativo', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_cesta_municipioentefederativo', to='comum.municipio')),
                ('municipio_local_armazenamento', smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='estado_local_armazenamento   ', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacao_cesta_municipio_local_armazenamento', to='comum.municipio')),
            ],
            options={
                'db_table': 'solicitacao_cestas_ada',
            },
        ),
        migrations.AlterField(
            model_name='arquivoscestas',
            name='solicitacaocestas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacaocestas', to='execucao.solicitacaocestasada'),
        ),
        migrations.DeleteModel(
            name='SolicitacaoCestaADA',
        ),
    ]
