# Generated by Django 4.1.7 on 2023-09-11 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('estado', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('ibge', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=155)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comum.estado')),
            ],
            options={
                'verbose_name': 'Município',
                'ordering': ['nome'],
            },
        ),
    ]
